---
- name: "install requirements.yml file (will always show 'no change')"
  community.general.ansible_galaxy_install:
    type: collection
    requirements_file: requirements.yml
  changed_when: false
