---
- name: 'install roles from requirements file'
  community.general.ansible_galaxy_install:
    type: collection
    requirements_file: requirements.yml
    state: latest
  register: ok
#  changed_when: ok.run_info.results_rc is defined and ok.run_info.results_rc != 0

- name: print
  debug:
    msg: "{{ ok }}"
