---
- name: 'install roles from requirements file'
  community.general.ansible_galaxy_install:
    type: collection
    requirements_file: requirements.yml
  register: test
  changed_when: test.rc != 0
