---
- name: 'install roles from requirements file'
  community.general.ansible_galaxy_install:
    type: collection
    requirements_file: requirements.yml
  register: ok
  changed_when: ok.results_rc != 0
